---
env:
  es6: true
  browser: true
extends:
  airbnb
globals:
  React: true
plugins:
  - react
rules:
  comma-dangle:
    - 2
    - never
  prefer-destructuring:
    - 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  react/no-danger:
    - 0
  one-var:
    - 0
